### PR TITLE
Adding an export module

### PR DESCRIPTION
**Pull request by jgostick**
Created stub code for a ``to_vtk`` function

### CODE REVIEW

**Comment by jgostick** [comment]
So is that finished? I recall that @mdrkok abandoned his output to Pallabos temporarily?

**Comment by mdrkok** [comment]
It's done I think, Tom modified the Palabos code to make it faster, I
haven't checked it if the output is still ok but I will,
Matt

**Comment by jgostick** [comment]
@mdrkok when checking, perhaps you could convert your checks in unit tests? 👍

**Comment by mdrkok** [comment]
Will do, just gotta figure out how to do that

**Pull request merged**
