### PR TITLE
General_bug_fixes

### PR DESCRIPTION
**Pull request by Zohaib-Atiq**
This pull request covers small bugs fixes in porespy

### CODE REVIEW

**Comment by jgostick** [comment]
any chance of address #48 in this PR?

**Comment by Zohaib-Atiq** [comment]
I think it is related to how we calculate geometrical properties in 2D images. Do you think it is a small fix?

**Comment by jgostick** [comment]
yes, I think you're right...it's not small enough.  Are there any other little bugs we can fix while we're at it though?

**Comment by jgostick** [comment]
Like #89

**Pull request merged**
