### PR TITLE
Sort imports using isort package

### PR DESCRIPTION
**Pull request by ma-sadeghi**

### CODE REVIEW

**Comment by ma-sadeghi** [comment]
@jgostick do you agree with this change?

**Comment by jgostick** [comment]
you ran isort on the code, but did you also add it to the actions or is this a one time thing?

**Comment by ma-sadeghi** [comment]
It's a one time thing, but I can add it as an Action if you think is important.

**Comment by jgostick** [comment]
No it's ok, i was just curious.  I think we could add it as an action when we also add yapf.  For now however, I think we should close this PR.  Let's do this as the very last thing before releasing 2.0.  This will cause too many conflicts with various things that are still being worked on, including the notebooks.

**Pull request closed without merging**
