### PR TITLE
Implement nphase_border filter to count number of uniquely numbered b…

### PR DESCRIPTION
**Pull request by TomTranter**
…ordering regions for each voxel in an image. Useful for finding triple-phase boundaries and junctions

### CODE REVIEW

**Comment by TomTranter** [comment]
@jgostick this is part one of the adjacent throat-neighbors. I need another function to loop through the triple-phase regions, dilating them by one and returning the actual values of the regions. This function just counts the number of unique bordering regions

**Comment by TomTranter** [comment]
@mdrkok check out this function. Might be useful for you for finding triple-phase boundaries

**Comment by TomTranter** [comment]
@jgostick this is ready to be merged

**Comment by jgostick** [comment]
except for the merge conflicts :-(

**Pull request merged**
