### PR TITLE
Fix `points_to_spheres` bug in 3D

### LINKED ISSUE #917: `points_to_spheres` not adding spheres correctly for 3D images
The function points_to_spheres is not correctly adding spheres for a 3D image.

```python
radius=10
im=np.full((41,41,41),0)
im[20,20,20]=radius

res_ps=ps.tools.points_to_spheres(im=im)
res_fixed = points_to_spheres_fixed(im=im)
print(f'Number voxels porespy: {np.sum(res_ps)}') # Number voxels porespy: 1
print(f'Number voxels fixed: {np.sum(res_fixed)}') # Number voxels fixed: 4169
print(f'Volume analytic: {4/3*radius**3 *np.pi}') # Volume analytic: 4188.790204786391

fig, ax = plt.subplots(3, 2, figsize=[12, 6])
ax[0,0].imshow(ps.visualization.sem(~res_ps, axis=0), interpolation='none', origin='lower')
ax[0,0].axis(False)
ax[1,0].imshow(ps.visualization.sem(~res_ps, axis=2).T, interpolation='none', origin='lower')
ax[1,0].axis(False);
ax[2,0].imshow(ps.visualization.sem(~res_ps, axis=1).T, interpolation='none', origin='lower')
ax[2,0].axis(False);

ax[0,1].imshow(ps.visualization.sem(~res_fixed, axis=0), interpolation='none', origin='lower')
ax[0,1].axis(False)
ax[1,1].imshow(ps.visualization.sem(~res_fixed, axis=2).T, interpolation='none', origin='lower')
ax[1,1].axis(False);
ax[2,1].imshow(ps.visualization.sem(~res_fixed, axis=1).T, interpolation='none', origin='lower')
ax[2,1].axis(False);
```

# Potential fix:
* remove '.T' in [_sphere_insertions.py#L38](https://github.com/PMEAL/porespy/blob/53a06d1cfccc2f37dd64a7962867edf3f765767f/porespy/tools/_sphere_insertions.py#L38)
* Add check for 'im.ndim==3' and  'r = im[x, y, z].flatten()' in  [_sphere_insertions.py#L48](https://github.com/PMEAL/porespy/blob/53a06d1cfccc2f37dd64a7962867edf3f765767f/porespy/tools/_sphere_insertions.py#L48)

# Fix used for example above
```python
def points_to_spheres_fixed(im):
    r"""
    Inserts disks/spheres into an image at locations indicated by non-zero values

    Parameters
    ----------
    im : ndarray
        The image containing nonzeros indicating the locations to insert spheres.
        If the non-zero values are `bool`, then the maximal size is found and used;
        if the non-zeros are `int` then these values are used as the radii.

    Returns
    -------
    spheres : ndarray
        A `bool` array with disks/spheres inserted at each nonzero location in `im`.
    """
    from scipy.spatial import distance_matrix
    if im.ndim == 3:
        x, y, z = np.where(im > 0)
        coords = np.vstack((x, y, z))
    else:
        x, y = np.where(im > 0)
        coords = np.vstack((x, y))
    if im.dtype == bool:
        dmap = distance_matrix(coords.T, coords.T)
        mask = dmap < 1
        dmap[mask] = np.inf
        r = np.around(dmap.min(axis=0)/2, decimals=0).astype(int)
    else:
        if im.ndim == 3:
            r = im[x, y, z].flatten()
        else:
            r = im[x, y].flatten()
    im_spheres = np.zeros_like(im, dtype=bool)
    im_spheres = ps.tools._insert_disks_at_points_parallel(
        im_spheres,
        coords=coords,
        radii=r,
        v=True,
        smooth=False,
    )
    return im_spheres
    ```

### PR DESCRIPTION
**Pull request by heinsimon**
Closes #917

### CODE REVIEW

**Review by ma-sadeghi — CHANGES_REQUESTED** [review]
Thanks for the PR. Could you please also add a unit test to test 2D vs. 3D behaviour?

**Comment by heinsimon** [comment]
I added a simple test case for 2D and 3D.

I did not add anything for im being a boolean array, since I do not really know what the expected output would be. It feels broken, but I do not know for sure.

**Comment by ma-sadeghi** [comment]
> I added a simple test case for 2D and 3D.
> 
> I did not add anything for im being a boolean array, since I do not really know what the expected output would be. It feels broken, but I do not know for sure.

That seems strange, I can't look at it right now, but will do later this week.

**Comment by heinsimon** [comment]
Is this PR still considered or is it outdated now?

**Comment by ma-sadeghi** [comment]
Sorry for the delay. I still didn't get the chance to review it. Will do this week hopefully.

**Comment by jgostick** [comment]
I'm so sorry how long this is taking.  Amin has a new job now, so it's all on me at the moment.  I think the PR is pretty much ready, I'll just go in and fix the tests myself asap.

**Comment by jgostick** [comment]
I see that "maintainers are allowed to edit this pull request" is enabled, but I honestly don't know how.  I would have expected to see this as a branch on my remote which I could pull locally to work on, but that is not how it works.  Soooo, I'm just going to merge it into dev, then create a new PR to fix the tests.

**Pull request merged**
