### PR TITLE
IBIP algorithm

### PR DESCRIPTION
**Pull request by Ni2M**
This PR handles the IBIP algorithm on CPU and GPU.

### CODE REVIEW

**Review by ma-sadeghi — CHANGES_REQUESTED** [review]
Good job @Ni2M, could you please change rename the gpu version of the methods you added to `_gpu` rather than `_g`? I think it's more descriptive. Thanks!

**Comment by Ni2M** [comment]
For sure, yes the naming _gpu is more descriptive. Thanks.

**Comment by Ni2M** [comment]
The PR is still under process. We are yet to determine final changes on how we are adding the ibip_gpu (whether to keep importing cupy,cupyx and dependency to cupy or alternatives).

**Comment by jgostick** [comment]
Yes, just get everything passing now, then we can finalize the naming and api during the devs meeting on Monday

**Comment by ma-sadeghi** [comment]
> The PR is still under process. We are yet to determine final changes on how we are adding the ibip_gpu (whether to keep importing cupy,cupyx and dependency to cupy or alternatives).

Just a few notes to be discussed during the dev meeting:
- I don't think GitHub CI machines have GPUs, I'm not sure if `cupy` can even be installed (maybe it can?)
- Since we can't assume that everyone has access to a dedicated Nvidia graphics card (`cupy`'s AMD support is experimental), I think it's best if we list `cupy` as an "optional" dependency, like `paraview`.

**Pull request merged**
