### PR TITLE
SNOW_partitioning_parallel

### PR DESCRIPTION
**Pull request by Zohaib-Atiq**
This branch introduces snow_partitioning_parallel filter in PoreSpy. This filter performs watershed in chunks to reduce computational time and RAM usage [ci min]

### CODE REVIEW

**Comment by Zohaib-Atiq** [comment]
@jgostick  why I am getting these test errors on travis. Is this a general issue?

**Comment by ma-sadeghi** [comment]
> @jgostick why I am getting these test errors on travis. Is this a general issue?

I'll push a fix soon. See #290 for details on the error.

**Comment by ma-sadeghi** [comment]
@Zohaib-Atiq Should be fixed now.

**Comment by ma-sadeghi** [comment]
@Zohaib-Atiq Can you please add some unit tests for these methods? `snow_partitioning_parallel`, `relabel_chunks`, `trim_internal_slice`, `copy`, `_replace`, `_sequence`

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi Thanks for the fix. I will add tests for some functions now.

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi I have already added a `snow_partitioning_parallel` test in the branch. The other functions are internal functions. They cannot be used independently. Do we need to add tests for these functions as well?

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi You also committed few changes in `pytest.ini`. PR was showing conflict with `dev` so changed it.

**Comment by ma-sadeghi** [comment]
> @ma-sadeghi I have already added a `snow_partitioning_parallel` test in the branch. The other functions are internal functions. They cannot be used independently. Do we need to add tests for these functions as well?

I added `"pragma: no cover"` directive to those methods for codecov not to count them towards coverage. Should work now.

Btw, is this PR ready to be merged?

**Pull request merged**
